---
title: "Plots Explored (GSS)"
output: html_document
date: "`r Sys.Date()`"
---


### initial setup
```{r echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
#initial setup
library(tidyverse)
library(plotly)
library(labelled)
library(readstata13)

#get data
gss22 <- read.dta13("GSSDashboard/GSS2022.dta")

#test vars
quant_var1 <- gss22$hrs1     #hours worked in a week
quant_var2 <- gss22$sibs     #number of siblings
cat_var1   <- gss22$wrkstat  #labor force status
cat_var2   <- gss22$wrkslf   #r self-emp or works for somebody
```


### Util Funcs
```{r}
#text wrapper for making sure labels are not too long
wrapp_text <- function(text, threshold = 20){
  
  output_vector <- c()
  
  for(text_element in text)
  {
  
    text_size <- nchar(text_element)
    #print(text_size)
    
    #if text not long enough to wrapp
    if(text_size <= threshold)
    {
      output_vector <- c(output_vector, text_element)
      next
    }
    
    #wrapp text
    else
    {
      output_str <- ""
      pos <- 1
      while(pos <= text_size)
      {
        start <- pos
        
        end <- start + threshold-1
        if(end > text_size){end = text_size}
        
        while(end < text_size & substring(text_element, end, end) != " ")
        { 
          end <- end + 1
        }
        
        temp_str <- substring(text_element, start, end)
        if(end != text_size)
        {
          temp_str <- paste(temp_str,"<br>", sep = "") #update the line
        }
        output_str <- paste(output_str, temp_str, sep = "") #update output string
        
        pos <- end + 1 #move to next part of the string
      }
      
      output_vector <- c(output_vector, output_str)
    }
  }
  return(output_vector)
}
```



### Quantitative variables:
```{r}
#single quantitative variable

#axis styles:
ax_hist <- list(
  title = "",
  zeroline = FALSE,
  showline = FALSE,
  showticklabels = TRUE,
  showgrid = FALSE
)

ax_box <- list(
  title = "",
  zeroline = FALSE,
  showline = FALSE,
  showticklabels = FALSE,
  showgrid = FALSE
)

subplot(
  plot_ly(x = ~quant_var1, type = "box", boxmean = TRUE,
          name = "") %>%
    layout(xaxis = ax_box, showlegend = FALSE),
  plot_ly(x = ~quant_var1, type = "histogram", histnorm = "percent",
          name = "", nbinsx = 9) %>% 
    layout(xaxis = ax_hist, yaxis = ax_hist),
  nrows = 2, heights = c(0.3, 0.7),
  shareX = TRUE
) %>%
  layout(showlegend = FALSE, title = "Distribution of X")
```

```{r}
#two quantitative variables
```


### Categorical variables:
```{r}
#one categorical variable
cat_values = data.frame(cat_name = cat_var1, quantity = 1) %>%
  dplyr::group_by(cat_name) %>%
  dplyr::summarise(total = sum(quantity)) %>%
  dplyr::mutate(cat_name = as.character(cat_name)) %>%
  dplyr::filter(!is.na(cat_name)) %>%
  dplyr::mutate(cat_name = wrapp_text(cat_name))


plot_ly(x = cat_values$cat_name,
        y = cat_values$total,
        type = "bar") %>%
  layout(xaxis = list(tickangle = 90))
```

```{r}
#two categorical variables with different categories
```

```{r}
#two categorica variables with same categories
```







